url: https://SteindlDaniel.github.io
baseurl:

# Site settings
title: Adventures24
email: steindl.d@gmx.at
description: "This is a website for the austrian company adventures24.at"


# Team names, titles and social links
people:
- name: Martin Reiter
  pic: 1
  position: Geschäftsführer / Gesellschafter
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: David Ablinger
  pic: 2
  position: Geschäftsführer / Gesellschafter
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Stefan Schuster
  pic: 3
  position: Geschäftsführer / Gesellschafter
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com
  - title: bitbucket 
    url: http://bitbucket.org
  - title: github
    url: http://github.com

# Postal address (add as many lines as necessary)
address:
  - line: 4872 Neukirchen an der Vöckla
  - line: Redl 13

# Build settings
markdown: kramdown
permalink: pretty
